"""Incident-response rule generation (SOAR playbook output).

The sensor sits behind a data diode and can never transmit, so these rules are
*exported* for an analyst to apply on the enforcement point on the production
side (firewall / IPS). Nothing here is executed by the pipeline.
"""
import ipaddress
import json
import re
import zlib
from typing import Dict, Any, List

LOCAL_SID_BASE = 9_000_000  # Snort/Suricata local rules live at sid >= 1,000,000

ENFORCEMENT_NOTE = (
    "# Generated by the passive diode-side sensor for the DOWNSTREAM enforcement point.\n"
    "# Review before applying; the sensor itself never transmits (zero return path)."
)


def _ip(value: Any):
    try:
        return ipaddress.ip_address(str(value))
    except ValueError:
        return None


def _rule_sid(alert: Dict[str, Any]) -> int:
    key = f"{alert.get('flow_id', '')}|{alert.get('threat_class', '')}|{alert.get('timestamp', '')}"
    return LOCAL_SID_BASE + zlib.crc32(key.encode("utf-8")) % 999_999


def _evidence(alert: Dict[str, Any]) -> Dict[str, Any]:
    ev = alert.get("evidence", {})
    if isinstance(ev, str):
        try:
            ev = json.loads(ev)
        except ValueError:
            ev = {}
    return ev if isinstance(ev, dict) else {}


def _safe_domain(text: Any) -> str:
    # Domains come from captured (attacker-controlled) traffic: keep only hostname characters so
    # nothing can break out of a rule option or the generated shell script
    return re.sub(r"[^A-Za-z0-9._-]", "", str(text))[:253]


def generate_response_rules(alert: Dict[str, Any]) -> Dict[str, str]:
    """Returns {"iptables": ..., "suricata": ..., "action": ...} for one alert."""
    threat = alert.get("threat_class", "")
    src, dst = _ip(alert.get("src_ip")), _ip(alert.get("dst_ip"))
    dst_port = int(alert.get("dst_port") or 0)
    proto = str(alert.get("protocol", "")).lower()
    proto = proto if proto in ("tcp", "udp") else "ip"
    ev = _evidence(alert)
    sid = _rule_sid(alert)
    ipt = "ip6tables" if (src and src.version == 6) or (dst and dst.version == 6) else "iptables"

    s_net = str(src) if src else "any"
    d_net = str(dst) if dst else "any"
    d_port = str(dst_port) if dst_port else "any"
    msg = f"SIH26145 {threat} {alert.get('severity', '')}".strip()

    iptables: List[str] = []
    suricata: List[str] = []
    action = ""

    if threat == "Volumetric_Protocol_DDoS":
        action = "Rate-limit new connections to the targeted service; block the heaviest sources."
        if dst:
            iptables.append(
                f"{ipt} -A INPUT -d {dst} -p tcp --syn -m hashlimit --hashlimit-name ddos_{sid} "
                f"--hashlimit-above 100/second --hashlimit-mode srcip -j DROP"
            )
        for top in ev.get("top_sources", [])[:5]:
            if _ip(top):
                iptables.append(f"{ipt} -A INPUT -s {top} -d {d_net} -j DROP")
        suricata.append(
            f'drop tcp any any -> {d_net} {d_port} (msg:"{msg} SYN flood"; flags:S,12; '
            f"detection_filter:track by_dst, count 300, seconds 1; sid:{sid}; rev:1;)"
        )

    elif threat == "Reconnaissance_Port_Scanning":
        action = "Block the scanning host and alert on further probes from it."
        if src:
            iptables.append(f"{ipt} -A INPUT -s {src} -j DROP")
        suricata.append(
            f'drop tcp {s_net} any -> any any (msg:"{msg} probe"; flags:S,12; '
            f"detection_filter:track by_src, count 10, seconds 3; sid:{sid}; rev:1;)"
        )

    elif threat == "Botnet_C2_Beaconing":
        action = "Cut the C2 channel and isolate the beaconing host for forensics."
        if src and dst:
            iptables.append(f"{ipt} -A FORWARD -s {src} -d {dst} -j DROP")
        if dst:
            iptables.append(f"{ipt} -A FORWARD -d {dst} -j DROP")
        suricata.append(f'drop {proto} {s_net} any -> {d_net} {d_port} (msg:"{msg} C2 check-in"; sid:{sid}; rev:1;)')

    elif threat == "DGA_Domains_and_DNS_Tunneling":
        domain = _safe_domain(ev.get("queried_domain", ""))
        action = "Sinkhole the domain at the resolver and investigate the querying host."
        # DNS encodes names as length-prefixed labels, so match the registered label, not the dotted name
        labels = [l for l in domain.split(".") if l]
        match_label = labels[-2] if len(labels) >= 2 else (labels[0] if labels else "")
        if src and match_label:
            iptables.append(
                f"{ipt} -A FORWARD -s {src} -p udp --dport 53 -m string --string {match_label} --algo bm -j DROP"
            )
        if domain:
            suricata.append(f'drop dns any any -> any any (msg:"{msg} {domain}"; dns.query; content:"{domain}"; nocase; sid:{sid}; rev:1;)')
            action += f" RPZ entry: {domain} CNAME ."

    elif threat == "Encrypted_Malware_TLS":
        ja3 = str(ev.get("ja3_hash", ""))
        ja3 = ja3 if re.fullmatch(r"[0-9a-f]{32}", ja3) else ""
        action = "Block the C2 endpoint and hunt for the same JA3 fingerprint elsewhere."
        if dst:
            port_opt = f" -p tcp --dport {dst_port}" if dst_port else ""
            iptables.append(f"{ipt} -A FORWARD -d {dst}{port_opt} -j DROP")
        if ja3:
            suricata.append(f'drop tls any any -> any any (msg:"{msg} JA3 {ja3}"; ja3.hash; content:"{ja3}"; sid:{sid}; rev:1;)')
        else:
            suricata.append(f'drop tls {s_net} any -> {d_net} {d_port} (msg:"{msg}"; sid:{sid}; rev:1;)')

    elif threat == "Data_Exfiltration":
        action = "Stop the outbound transfer and preserve the host for incident response."
        if src and dst:
            iptables.append(f"{ipt} -A FORWARD -s {src} -d {dst} -j DROP")
        suricata.append(
            f'drop {proto} {s_net} any -> {d_net} {d_port} (msg:"{msg} bulk egress"; dsize:>1000; '
            f"detection_filter:track by_src, count 20, seconds 5; sid:{sid}; rev:1;)"
        )

    else:
        action = "Review the flow manually."
        if src:
            iptables.append(f"{ipt} -A INPUT -s {src} -j LOG --log-prefix \"SIH26145 \"")

    return {
        "action": action,
        "iptables": "\n".join(iptables),
        "suricata": "\n".join(suricata),
        "sid": str(sid),
    }


def build_rules_bundle(alerts: List[Dict[str, Any]]) -> Dict[str, str]:
    """Deduplicated shell script + rules file for a set of alerts."""
    seen_ipt, seen_rules = set(), set()
    ipt_lines, rule_lines = [], []
    for alert in alerts:
        rules = generate_response_rules(alert)
        header = f"# alert {alert.get('id', '')} {alert.get('threat_class', '')} {alert.get('flow_id', '')}"
        new_ipt = [l for l in rules["iptables"].splitlines() if l and l not in seen_ipt]
        new_rules = [l for l in rules["suricata"].splitlines() if l and l not in seen_rules]
        seen_ipt.update(new_ipt)
        seen_rules.update(new_rules)
        if new_ipt:
            ipt_lines += [header] + new_ipt
        if new_rules:
            rule_lines += [header] + new_rules
    return {
        "iptables_sh": "#!/bin/sh\n" + ENFORCEMENT_NOTE + "\nset -e\n" + "\n".join(ipt_lines) + "\n",
        "suricata_rules": ENFORCEMENT_NOTE + "\n" + "\n".join(rule_lines) + "\n",
    }
